### Numpy

In [1]:
# Importando a biblioteca Numpy
import numpy as np

In [2]:
# Criando um array (lista) usando a biblioteca Numpy
arr_list = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr_list)

[1 2 3 4 5 6 7 8]


In [3]:
# Criando uma matriz
arr_zeros = np.zeros((4,6)) # 4 linhas e 6 colunas preenchidas com zeros
print(arr_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
arr_ones = np.ones((3,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
# Criando uma matriz randomica
arr_random = np.random.rand(3, 4)
print(arr_random)

[[0.59268573 0.79162494 0.65010172 0.0215184 ]
 [0.79577285 0.26656718 0.0198567  0.29874456]
 [0.51836615 0.91459589 0.27076956 0.71905336]]


In [6]:
print(arr_random.shape)

(3, 4)


In [7]:
array_random_reshape = arr_random.reshape((4, 3))
print(array_random_reshape)

[[0.59268573 0.79162494 0.65010172]
 [0.0215184  0.79577285 0.26656718]
 [0.0198567  0.29874456 0.51836615]
 [0.91459589 0.27076956 0.71905336]]


In [8]:
# Criando matrizes 2D
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

In [9]:
arr1

array([[1, 2],
       [3, 4]])

In [10]:
# Concatenando as matrizes horizontalmente (axis=1)
arr4 = np.concatenate((arr1, arr2, arr3), axis=1)
arr4

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [11]:
# Separando os arrays em 2 partes iguais
arr4_split = np.split(arr4, 2)
print(arr4_split)

[array([[ 1,  2,  5,  6,  9, 10]]), array([[ 3,  4,  7,  8, 11, 12]])]


In [12]:
# Realizando trasposição da matriz arr4
arr4_transpose = np.transpose(arr4)
print(arr4_transpose)

[[ 1  3]
 [ 2  4]
 [ 5  7]
 [ 6  8]
 [ 9 11]
 [10 12]]


In [13]:
# Revertendo o valor 
arr4_revertido = arr4_transpose.T
arr4_revertido

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [14]:
# Somando os arrays
arr_a = np.array([1, 7, 28])
arr_b = np.array([1, 5, 8])

In [15]:
arr_a_b = np.add(arr_a, arr_b)
arr_a_b

array([ 2, 12, 36])

In [16]:
arr_sub_a_b = np.subtract(arr_a, arr_b)
arr_sub_a_b

array([ 0,  2, 20])